=== De9ine/WaveMVC/plugin.dtd
<!ELEMENT plugin
  (name,class,version,dependencies,hooks, endpoints)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT dependencies (#PCDATA)>

<!ELEMENT hooks 
  (hook)>
<!ELEMENT hook EMPTY>
<!ATTLIST hook 
  name CDATA ""
  callback CDATA ""
  >

<!ELEMENT endpoints (endpoint*)>
<!ELEMENT endpoint (argument*)>
<!ATTLIST endpoint
  path CDATA ""
  callback CDATA ""
  >
<!ELEMENT argument (#PCDATA)>

=== De9ine/WaveMVC/core/node/manifest.xml
<!DOCTYPE plugin SYSTEM "../../plugin.dtd">
<plugin>
  <name>Node</name>
  <class>Node</class>
  <version>1.x</version>
  <dependencies></dependencies>
  <hooks>
    <hook name="preprocess_theme_vars" callback="preprocess_theme_vars" />
  </hooks>
  <endpoints>
    <endpoint path="node" callback="node">
    </endpoint>
  </endpoints>
</plugin>
