=== De9ine/WaveMVC/site.dtd
<!ELEMENT site
  (classpath, name,scripts*, baseurl, theme, db, endpoints)>
<!ELEMENT classpath (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT scripts (script)>
<!ELEMENT baseurl (#PCDATA)>
<!ELEMENT theme (#PCDATA)>
<!ELEMENT script (#PCDATA)>
<!ELEMENT db (user, passwd, host, handler, database)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT passwd (#PCDATA)>
<!ELEMENT host (#PCDATA)>
<!ELEMENT handler (#PCDATA)>
<!ELEMENT database (#PCDATA)>

<!ELEMENT endpoints (endpoint*)>
<!ELEMENT endpoint (argument*)>
<!ATTLIST endpoint
  path CDATA ""
  callback CDATA ""
  >
  
<!ELEMENT argument (#PCDATA)>

=== De9ine/WaveMVC/manifest.xml
<!DOCTYPE site SYSTEM "site.dtd">
<site>
  <classpath>src/Main.php</classpath>
  <name>a</name>
  <scripts><script>a</script></scripts>
  <baseurl>http://localhost/workspace2/mvc/</baseurl>
  <theme>generic</theme>
  <db>
    <user>root</user>
    <passwd>toor</passwd>
    <host>127.0.0.1</host>
    <handler>default</handler>
    <database>mvc</database>
  </db>
  <endpoints>
    <endpoint path="/" callback="Front">
    </endpoint>
    <endpoint path="apa" callback="Front">
    </endpoint>
  </endpoints>
</site>
